[package]
name = "rqbit"
version = "0.1.0"
authors = ["Igor Katson <igor.katson@gmail.com>"]
edition = "2018"

[features]
rt-single-thread = []

[dependencies]
librqbit = {path="./crates/librqbit"}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
anyhow = "1"
clap = "3.0.0-beta.2"
log = "0.4"
pretty_env_logger = "0.4"
reqwest = "0.11"
regex = "1"

[dev-dependencies]
futures = {version = "0.3"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"