[package]
name = "bencode"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features=["derive"]}
buffers = {path = "../buffers"}
clone_to_owned = {path = "../clone_to_owned"}
anyhow = "1"
sha1w = {path="../sha1w"}