[package]
name = "librqbit"
version = "0.1.0"
authors = ["Igor Katson <igor.katson@gmail.com>"]
edition = "2018"

[features]
default = ["sha1-openssl"]
sha1-system = ["crypto-hash"]
sha1-openssl = ["openssl"]
sha1-rust = ["sha1"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencode = {path = "../bencode"}
buffers = {path = "../buffers"}
librqbit_core = {path = "../librqbit_core"}
clone_to_owned = {path = "../clone_to_owned"}
peer_binary_protocol = {path = "../peer_binary_protocol"}
sha1w = {path = "../sha1w"}

tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
serde = {version = "1", features=["derive"]}
anyhow = "1"

reqwest = "0.11"
urlencoding = "1"
byteorder = "1"
bincode = "1"
bitvec = "0.22"
parking_lot = "0.11"
log = "0.4"
size_format = "1"
rand = "0.8"
warp = "0.3"

openssl = {version="0.10", optional=true}
crypto-hash = {version="0.3", optional=true}
sha1 = {version = "0.6", optional=true}

uuid = {version = "0.8", features = ["v4"]}
futures = "0.3"
url = "2"
hex = "0.4"

[dev-dependencies]
futures = {version = "0.3"}
pretty_env_logger = "0.4"