[package]
name = "librqbit"
version = "0.1.0"
authors = ["Igor Katson <igor.katson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
serde = {version = "1", features=["derive"]}
anyhow = "1"
sha1 = "0.6"
reqwest = "0.11"
urlencoding = "1"
byteorder = "1"
bincode = "1"
bitvec = "0.22"
parking_lot = "0.11"
log = "0.4"
size_format = "1"
rand = "0.8"

uuid = {version = "0.8", features = ["v4"]}
futures = "0.3"

[dev-dependencies]
futures = {version = "0.3"}
pretty_env_logger = "0.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"