[package]
name = "dht"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kad = "0.6"
tokio = {version = "1", features = ["macros", "rt"]}
serde = {version = "1", features = ["derive"]}
hex = "0.4"
bencode = {path = "../bencode"}
anyhow = "1"